.core-defs:
  variables:
    CORENAME: vbam

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile

libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile
    
# Static
libretro-build-vita:
  extends:
    - .core-defs
    - .libretro-vita-static-retroarch-master
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile
